export const products = [
    {
        id: 1,
        title: "Wireless Headphones",
        category: "Electronics",
        price: 59.99,
        image: "https://picsum.photos/id/1011/200/200",
        descr: "Comfortable wireless headphones with noise cancellation and deep bass.",
    },
    {
        id: 2,
        title: "Running Shoes",
        category: "Sports",
        price: 89.99,
        image: "https://picsum.photos/id/1025/200/200",
        descr: "Lightweight running shoes with breathable material and strong grip.",
    },
    {
        id: 3,
        title: "Coffee Maker",
        category: "Home Appliances",
        price: 129.99,
        image: "https://picsum.photos/id/1060/200/200",
        descr: "Automatic drip coffee maker with timer and 12-cup capacity.",
    },
    {
        id: 4,
        title: "Smart Watch",
        category: "Electronics",
        price: 199.99,
        image: "https://picsum.photos/id/1005/200/200",
        descr: "Track your fitness, heart rate, and sleep patterns with ease.",
    },
    {
        id: 5,
        title: "Backpack",
        category: "Accessories",
        price: 39.99,
        image: "https://picsum.photos/id/1044/200/200",
        descr: "Durable backpack with multiple compartments and water-resistant material.",
    },
    {
        id: 6,
        title: "Electric Kettle",
        category: "Home Appliances",
        price: 34.99,
        image: "https://picsum.photos/id/1069/200/200",
        descr: "1.7L stainless steel electric kettle with automatic shut-off feature.",
    },
    {
        id: 7,
        title: "Gaming Mouse",
        category: "Electronics",
        price: 49.99,
        image: "https://picsum.photos/id/1080/200/200",
        descr: "Ergonomic gaming mouse with customizable buttons and RGB lighting.",
    },
    {
        id: 8,
        title: "Yoga Mat",
        category: "Sports",
        price: 25.99,
        image: "https://picsum.photos/id/1084/200/200",
        descr: "Non-slip yoga mat with extra thickness for comfort and stability.",
    },
    {
        id: 9,
        title: "Sunglasses",
        category: "Accessories",
        price: 19.99,
        image: "https://picsum.photos/id/1027/200/200",
        descr: "Stylish polarized sunglasses with UV protection.",
    },
    {
        id: 10,
        title: "Bluetooth Speaker",
        category: "Electronics",
        price: 79.99,
        image: "https://picsum.photos/id/1010/200/200",
        descr: "Portable Bluetooth speaker with powerful sound and long battery life.",
    },
];
